# Generated by Django 5.2.7 on 2025-10-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_remove_cliente_bairro_alter_cliente_cidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='numero',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(default="Santa Barbara D'Oeste", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cliente',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='contato',
            field=models.CharField(default="Santa Barbara D'Oeste", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='responsavel',
            field=models.CharField(default="Santa Barbara D' Oeste", max_length=255),
            preserve_default=False,
        ),
    ]
