# Generated by Django 5.2.6 on 2025-10-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_cliente_bairro_cliente_cep_cliente_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
