# Generated by Django 5.0.1 on 2025-10-12 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_cliente_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cep',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='contato',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='responsavel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
