# Generated by Django 5.0.1 on 2025-10-08 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='contato',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='tipoPedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo',
            field=models.CharField(choices=[('Entrega', 'Entrega'), ('Retirada', 'Retirada')], default='Entrega', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='endereco',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='responsavel',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('entregue', 'Entregue')], default='pendente', max_length=20),
        ),
        migrations.CreateModel(
            name='ProdutoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('qtd', models.FloatField()),
                ('valorUnit', models.FloatField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='pedidos.pedido')),
            ],
        ),
        migrations.DeleteModel(
            name='MaterialPedido',
        ),
    ]
